<?xml version="1.0"?>
<!--
  Copyright 2002-2004 The Apache Software Foundation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE plugins [
  <!ENTITY % links.att 'name CDATA #REQUIRED'>
  <!ENTITY % link.att 'name CDATA #REQUIRED href CDATA #REQUIRED'>
  <!ELEMENT plugins (plugin*)>
  <!ELEMENT plugin (description)>
  <!ATTLIST plugin name CDATA #REQUIRED
                 url  CDATA #REQUIRED
                 author CDATA #REQUIRED
                 website CDATA #IMPLIED>
  <!ELEMENT description (#PCDATA)>
  ]>
  
<plugins>
  
  <plugin name="feeder"
        author="Ross Gardler"
        website="http://www.burrokeet.org"
        url="http://www.apache.org/~rgardler/testingGround/forrestPlugins/">
    <description>
      Embed syndicated content in a Forrest site. 
    </description>
  </plugin>
  
  <plugin name="IMSManifest"
        author="Ross Gardler"
        website="http://www.burrakeet.org"
        url="http://www.apache.org/~rgardler/testingGround/forrestPlugins/">

    <description>
      Use an IMS Manifest file to manage site structure. Generates site.xml and
      tabs.xml from an imsmanifest.xml file when one is available.
      
      Also enables content in one Content Packge to be embedded in another.
    </description>
  </plugin>
  
  <plugin name="OpenOffice.org"
        author="Apache Forrest Project"
        website="http://forrest.apache.org/plugins/OpenOffice.org"
        url="http://www.apache.org/~rgardler/testingGround/forrestPlugins/">
    <description>
      Embed OpenOffice.org application content in a Forrest site. 
    </description>
  </plugin>
  
  <plugin name="simplified-docbook"
        author="Apache Forrest Project"
        website="http://forrest.apache.org/plugins/simplified-docbook"
        url="http://www.apache.org/~rgardler/testingGround/forrestPlugins/">
    <description>
      Support of Simplified Docbook files.
    </description>
  </plugin>
</plugins>
