<?xml version="1.0"?>
<!--
  Copyright 2002-2004 The Apache Software Foundation or its licensors,
  as applicable.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE plugins [
  <!ENTITY % links.att 'name CDATA #REQUIRED'>
  <!ENTITY % link.att 'name CDATA #REQUIRED href CDATA #REQUIRED'>
  <!ELEMENT plugins (plugin*)>
  <!ATTLIST plugins type CDATA #REQUIRED>
  <!ELEMENT plugin (description, forrestVersion)>
  <!ATTLIST plugin name CDATA #REQUIRED
                 type (input|output|internal) #REQUIRED
                 url  CDATA #REQUIRED
                 author CDATA #REQUIRED
                 website CDATA #IMPLIED
                 version CDATA #IMPLIED>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT forrestVersion (#PCDATA)>
  ]>

<plugins type="whiteboard">

<!-- ================================================================== -->
<!-- Input Plugins                                                      -->
<!-- ================================================================== -->  

  <plugin name="org.apache.forrest.plugin.input.Daisy"
        type="input"
        author="Apache Forrest Project"
        website="http://forrest.apache.org/pluginDocs/plugins_0_70/org.apache.forrest.plugin.input.Daisy/"
        url="http://forrest.apache.org/plugins"
        version="0.1-dev">
    <description>
      Allow content to be included from a Daisy CMS repository.
    </description>
    <forrestVersion>0.7</forrestVersion>
  </plugin>

  <plugin name="org.apache.forrest.plugin.input.logs"
        type="input"
        author="Apache Forrest Project"
        website="http://forrest.apache.org/pluginDocs/plugins_0_70/org.apache.forrest.plugin.input.logs"
        url="http://forrest.apache.org/plugins"
        version="0.1-dev">
    <description>
      Embed log file output in Forrest sites. If Forrest is running in a
      dynamic environment, then pages can be updated to show recent changes in the 
      log whenever required.
    </description>
    <forrestVersion>0.7</forrestVersion>
  </plugin>

<!-- ================================================================== -->
<!-- Output Plugins                                                     -->
<!-- ================================================================== -->

  <plugin name="org.apache.forrest.plugin.output.Chart"
        type="output"
        author="Apache Forrest Project"
        website="http://forrest.apache.org/pluginDocs/plugins_0_70/org.apache.forrest.plugin.output.Chart"
        url="http://forrest.apache.org/plugins/"
        version="0.1-dev">
    <description>
      Charting plugin that utilises JChart. 
    </description>
    <forrestVersion>0.7</forrestVersion>
  </plugin>

  <plugin name="org.apache.forrest.plugin.output.htmlArea"
        type="output"
        author="Apache Forrest Project"
        website="http://forrest.apache.org/pluginDocs/plugins_0_70/org.apache.forrest.plugin.output.htmlArea"
        url="http://forrest.apache.org/plugins/"
        version="0.1-dev">
    <description>
      WYSIWYG editing of HTML documents (requires Forrest to be running dynamically). 
    </description>
    <forrestVersion>0.7</forrestVersion>
  </plugin>
  
  <plugin name="org.apache.forrest.plugin.output.voice"
        type="output"
        author="Apache Forrest Project"
        website="http://forrest.apache.org/pluginDocs/plugins_0_70/org.apache.forrest.plugin.output.Chart"
        url="http://forrest.apache.org/plugins/"
        version="0.1-dev">
    <description>
      Add voiceXML content to a Forrest page. This allows the page to be read by a voice synthesiser
      and navigated with voice commands.
    </description>
    <forrestVersion>0.8-dev</forrestVersion>
  </plugin>

  <!-- ================================================================== -->
  <!-- Internal Plugins                                                   -->
  <!-- ================================================================== -->

  <plugin name="org.apache.forrest.plugin.internal.view"
        type="internal"
        author="Apache Forrest Project"
        website="http://forrest.apache.org/pluginDocs/plugins_0_70/org.apache.forrest.plugin.view"
        url="http://forrest.apache.org/plugins/"
        version="0.1-dev">
    <description>
      Enable Forrest to use page-specific views and contracts. Next generation skinning.
    </description>
    <forrestVersion>0.7</forrestVersion>
  </plugin>

</plugins>
