<?xml version="1.0"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE skins [
  <!ENTITY % links.att 'name CDATA #REQUIRED'>
  <!ENTITY % link.att 'name CDATA #REQUIRED href CDATA #REQUIRED'>
  <!ELEMENT skins (skin*)>
  <!ELEMENT skin (description)>
  <!ATTLIST skin name CDATA #REQUIRED
                 url  CDATA #REQUIRED
                 author CDATA #REQUIRED
                 website CDATA #IMPLIED>
  <!ELEMENT description (#PCDATA)>
  ]>
<skins>
  <skin name="testskin"
        author="Nicola Ken Barozzi"
        website="http://www.nicolaken.com"
        url="http://www.apache.org/~nicolaken/whiteboard/forrestskins/">
    <description>
      Based on the standard forrest-site skin. (Note: This is only a test skin,
      with trivial changes to demonstrate the concept.)
    </description>
  </skin>
  <skin name="testskin2"
        author="Nicola Ken Barozzi"
        website="http://www.nicolaken.com"
        url="http://www.apache.org/~nicolaken/whiteboard/forrestskins/">
    <description>
      Based on the standard forrest-site skin. (Note: This is only a test skin,
      with trivial changes to demonstrate the concept.)
    </description>
  </skin>
</skins>
